name: app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^9.2.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.4
  get_it: ^9.2.1
  go_router: ^17.1.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  json_annotation: ^4.11.0
  path: ^1.9.1
  path_provider: ^2.1.5
  retrofit: ^4.9.2
  talker: ^5.1.15
  talker_bloc_logger: ^5.1.15
  talker_dio_logger: ^5.1.15
  talker_flutter: ^5.1.15
  talker_logger: ^5.1.15

dev_dependencies:
  build: ^4.0.4
  build_runner: ^2.12.2
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.11.1
  json_serializable: ^6.13.0
  retrofit_generator: ^10.2.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - ".env"

    - "assets/svg/house.svg"
    - "assets/svg/search.svg"
    - "assets/svg/heart.svg"
    - "assets/svg/user.svg"

    - "assets/images/a12_branding.png"
    - "assets/images/a12_splash.png"
    - "assets/images/branding.png"
    - "assets/images/splash.png"

  fonts:
    - family: Manrope
      fonts:
        - asset: "assets/fonts/Manrope/Manrope-ExtraBold.ttf"
          weight: 800
        - asset: "assets/fonts/Manrope/Manrope-Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Manrope/Manrope-SemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/Manrope/Manrope-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/Manrope/Manrope-Regular.ttf"
          weight: 400
        - asset: "assets/fonts/Manrope/Manrope-Light.ttf"
          weight: 300
        - asset: "assets/fonts/Manrope/Manrope-ExtraLight.ttf"
          weight: 200

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash.png"
  branding: "assets/images/branding.png"

  color_dark: "#000000"
  image_dark: "assets/images/splash.png"
  branding_dark: "assets/images/branding.png"

  android_12:
    color: "#ffffff"
    icon_background_color: "#000000"
    image: "assets/images/a12_splash.png"
    branding: "assets/images/a12_branding.png"

    color_dark: "#000000"
    icon_background_color_dark: "#ffffff"
    image_dark: "assets/images/a12_splash.png"
    branding_dark: "assets/images/a12_branding.png"

  android: true
  ios: true
  web: true
